### ISSUE TITLE
Issue while running `pronto run -f github_pr -c origin/master`

### ISSUE THREAD

**Issue by peeyushsingla** [prontolabs/pronto#182]
I am trying to run 

`GITHUB_ACCESS_TOKEN=MYTOKENGOESHERE pronto run -f github_pr -c origin/master`

If we have lots of issues/comments to be made on the pull request it will throw timeout exception although it is posting all those comments but it throw timeout error without completing posting all the errors.

`Users/peeyush/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:880:in 'initialize': execution expired (Faraday::ConnectionFailed)
  from /Users/peeyush/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:880:in 'open'
  from /Users/peeyush/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:880:in 'block in connect'
  from /Users/peeyush/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:101:in 'timeout'
  from /Users/peeyush/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:878:in 'connect'
  from /Users/peeyush/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:863:in 'do_start'
  from /Users/peeyush/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:852:in 'start'
  from /Users/peeyush/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:1398:in 'request'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in 'perform_request'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in 'block in call'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in 'with_net_http_connection'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in 'call'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/faraday-0.9.2/lib/faraday/response.rb:8:in 'call'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/faraday-0.9.2/lib/faraday/response.rb:8:in 'call'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:73:in 'perform_with_redirection'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:61:in 'call'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in 'build_response'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in 'run_request'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in 'post'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/sawyer-0.7.0/lib/sawyer/agent.rb:94:in 'call'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/octokit-4.3.0/lib/octokit/connection.rb:154:in 'request'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/octokit-4.3.0/lib/octokit/connection.rb:28:in 'post'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/octokit-4.3.0/lib/octokit/client/pull_requests.rb:211:in 'create_pull_request_comment'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/pronto-0.7.1/lib/pronto/github.rb:35:in 'create_pull_comment'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/pronto-0.7.1/lib/pronto/formatter/pull_request_formatter.rb:14:in 'block in submit_comments'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/pronto-0.7.1/lib/pronto/formatter/pull_request_formatter.rb:14:in 'each'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/pronto-0.7.1/lib/pronto/formatter/pull_request_formatter.rb:14:in 'submit_comments'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/pronto-0.7.1/lib/pronto/formatter/git_formatter.rb:10:in 'format'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/pronto-0.7.1/lib/pronto.rb:59:in 'block in run'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/pronto-0.7.1/lib/pronto.rb:58:in 'each'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/pronto-0.7.1/lib/pronto.rb:58:in 'run'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/pronto-0.7.1/lib/pronto/cli.rb:54:in 'block in run'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/pronto-0.7.1/lib/pronto/cli.rb:53:in 'chdir'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/pronto-0.7.1/lib/pronto/cli.rb:53:in 'run'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/thor-0.19.1/lib/thor/command.rb:27:in 'run'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/thor-0.19.1/lib/thor/invocation.rb:126:in 'invoke_command'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/thor-0.19.1/lib/thor.rb:359:in 'dispatch'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/thor-0.19.1/lib/thor/base.rb:440:in 'start'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/gems/pronto-0.7.1/bin/pronto:6:in '<top (required)>'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/bin/pronto:23:in 'load'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/bin/pronto:23:in '<main>'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/bin/ruby_executable_hooks:15:in 'eval'
  from /Users/peeyush/.rvm/gems/ruby-2.3.0@steps/bin/ruby_executable_hooks:15:in '<main>'`

**Comment by mmozuras** [comment]
@peeyushsingla at how many comments, do the timeouts start occurring? Could it be that you're hitting GitHub [rate limit](https://developer.github.com/v3/rate_limit/)?

**Comment by mmozuras** [comment]
@peeyushsingla we've added `github_pr_review` formatter. It will be released in `v0.9.0`. You can also try it out by building the gem yourself locally. It uses Reviews API, which posts all the comments with a single request. Should work around this issue 🙂.

**Comment by Schwad** [comment]
@peeyushsingla do you feel that this issue has been resolved by the formatter released in `v0.9.0` or does this issue need to remain open?
