### ISSUE TITLE
Uninitialized constant Pronto::Formatter::SimpleDelegator

### ISSUE THREAD

**Issue by hmnhf** [prontolabs/pronto#229]
Hi, I'm getting this error when trying to run pronto.

```
~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.1/lib/pronto/formatter/text_message_decorator.rb:5:in `<module:Formatter>': uninitialized constant Pronto::Formatter::SimpleDelegator (NameError)
from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.1/lib/pronto/formatter/text_message_decorator.rb:4:in `<module:Pronto>'
from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.1/lib/pronto/formatter/text_message_decorator.rb:3:in `<top (required)>'
from ~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from ~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.1/lib/pronto/formatter/text_formatter.rb:1:in `<top (required)>'
from ~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from ~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.1/lib/pronto.rb:38:in `<top (required)>'
from ~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
from ~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.1/bin/pronto:3:in `<top (required)>'
from ~/.rbenv/versions/2.3.1/bin/pronto:23:in `load'
from ~/.rbenv/versions/2.3.1/bin/pronto:23:in `<main>'
```

As a temporary fix, I'm requiring `delegate` in `lib/pronto/formatter/text_message_decorator.rb` .

**Comment by mmozuras** [comment]
@aergonaut hey, could you take a loot at this issue? 🙂

**Comment by aergonaut** [comment]
Yep!

**Comment by kasiakasprzak** [comment]
+ 1
