### ISSUE TITLE
Bitbucket Server Formatter defaults to port 80 and can't be changed

### ISSUE THREAD

**Issue by corroded** [prontolabs/pronto#237]
Hi, I am trying to make pronto work with our internal Stash installation but it doesn't seem to connect to our server. I've tried to trace the errors by looking at the stack trace and it looks like it just assumes port 80.

Here is my stacktrace:

```
$ pronto run -f bitbucket_server_pr -c origin/develop                                                  [2.3.1]
/Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect': Failed to open TCP connection to :80 (Connection refused - connect(2) for nil port 80) (Errno::ECONNREFUSED)
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:1398:in `request'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty/request.rb:118:in `perform'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty.rb:560:in `perform_request'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty.rb:486:in `get'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/clients/bitbucket_server_client.rb:65:in `get'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/clients/bitbucket_server_client.rb:40:in `block (2 levels) in paged_request'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/clients/bitbucket_server_client.rb:39:in `loop'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/clients/bitbucket_server_client.rb:39:in `block in paged_request'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/bitbucket_server.rb:27:in `each'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/bitbucket_server.rb:27:in `each'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/bitbucket_server.rb:27:in `find'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/bitbucket_server.rb:27:in `pull'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/bitbucket.rb:54:in `pull_id'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/bitbucket_server.rb:4:in `pull_comments'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/formatter/pull_request_formatter.rb:6:in `existing_comments'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/formatter/git_formatter.rb:6:in `format'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto.rb:67:in `block in run'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto.rb:66:in `each'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto.rb:66:in `run'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/cli.rb:61:in `block in run'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/cli.rb:60:in `chdir'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/cli.rb:60:in `run'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/bin/pronto:6:in `<top (required)>'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/bin/pronto:23:in `load'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/bin/pronto:23:in `<main>'
```

Let me know if you need more info. I've set the `.pronto.yml` to:

```
all:
  exclude:
    - 'spec/**/*'
# exclude files for single runner
eslint:
  exclude:
    - 'app/assets/**/*'
bitbucket:
  slug: repo/site
  username: user
  password: pass
  web_endpoint: http://stash.localhost:7990
max_warnings: 150
verbose: false
```

Upon further investigation, it looks like it is hitting Bitbucket via HTML instead of JSON as well. I tried hard-coding our URI by adding `base_uri 'http://stash.localhost:7990/'` to `pronto-0.9.3/lib/pronto/clients/bitbucket_server_client.rb` but now it explodes because 

```
  def get(url, query)
    self.class.get(url, query).parsed_response
  end
```

gets an HTML page instead of a JSON response - prompting it to error with: 

```
pronto-0.9.3/lib/pronto/clients/bitbucket_server_client.rb:48:in `block (2 levels) in paged_request': undefined method `each' for "values":String (NoMethodError)
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/clients/bitbucket_server_client.rb:44:in `loop'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/clients/bitbucket_server_client.rb:44:in `block in paged_request'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/bitbucket_server.rb:27:in `each'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/bitbucket_server.rb:27:in `each'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/bitbucket_server.rb:27:in `find'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/bitbucket_server.rb:27:in `pull'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/bitbucket.rb:54:in `pull_id'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/bitbucket_server.rb:4:in `pull_comments'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/formatter/pull_request_formatter.rb:6:in `existing_comments'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/formatter/git_formatter.rb:6:in `format'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto.rb:67:in `block in run'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto.rb:66:in `each'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto.rb:66:in `run'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/cli.rb:61:in `block in run'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/cli.rb:60:in `chdir'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/lib/pronto/cli.rb:60:in `run'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pronto-0.9.3/bin/pronto:6:in `<top (required)>'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/bin/pronto:23:in `load'
	from /Users/eumirgaspar/.rbenv/versions/2.3.1/bin/pronto:23:in `<main>'
```

pretty sure I just might be missing something here...

**Comment by ivanovaleksey** [comment]
Hi @corroded,

I don't have experience about Pronto with BitBucket, but it seems like `BitbucketServerClient` instance [should be initialized](https://github.com/prontolabs/pronto/blob/master/lib/pronto/bitbucket_server.rb#L18) with API URL.
Your `http://stash.localhost:7990` is most likely BitBucket itself not API.

Have you tried to specify `api_endpoint` for BitBucket in configuration file?

**Comment by corroded** [comment]
Looks like we have been in an older version of BitBucket (v4) so no API integration yet. Closing this now.
