### ISSUE TITLE
github_pr throwing 404 error

### ISSUE THREAD

**Issue by nagarjunac** [prontolabs/pronto#248]
I am running this command 
GITHUB_ACCESS_TOKEN=xxxxxxxx PRONTO_PULL_REQUEST_ID=4 bundle exec pronto run -c origin/opsworks_provision -f github_pr 
which is throwing the below error. Unable to resolve it.Please help.

/usr/share/rvm/gems/ruby-2.3.0/gems/octokit-4.7.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/Voonik/devops_tools/pulls?per_page=100: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)
	from /usr/share/rvm/gems/ruby-2.3.0/gems/faraday-0.10.1/lib/faraday/response.rb:9:in `block in call'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/faraday-0.10.1/lib/faraday/response.rb:61:in `on_complete'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/faraday-0.10.1/lib/faraday/response.rb:8:in `call'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/octokit-4.7.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/octokit-4.7.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/faraday-0.10.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/faraday-0.10.1/lib/faraday/connection.rb:377:in `run_request'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/faraday-0.10.1/lib/faraday/connection.rb:140:in `get'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/octokit-4.7.0/lib/octokit/connection.rb:156:in `request'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/octokit-4.7.0/lib/octokit/connection.rb:84:in `paginate'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/octokit-4.7.0/lib/octokit/client/pull_requests.rb:20:in `pull_requests'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/pronto-0.9.3/lib/pronto/github.rb:97:in `pull_requests'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/pronto-0.9.3/lib/pronto/github.rb:90:in `pull'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/pronto-0.9.3/lib/pronto/github.rb:81:in `pull_id'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/pronto-0.9.3/lib/pronto/github.rb:12:in `rescue in pull_comments'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/pronto-0.9.3/lib/pronto/github.rb:4:in `pull_comments'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/pronto-0.9.3/lib/pronto/formatter/pull_request_formatter.rb:6:in `existing_comments'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/pronto-0.9.3/lib/pronto/formatter/git_formatter.rb:6:in `format'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/pronto-0.9.3/lib/pronto.rb:67:in `block in run'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/pronto-0.9.3/lib/pronto.rb:66:in `each'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/pronto-0.9.3/lib/pronto.rb:66:in `run'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/pronto-0.9.3/lib/pronto/cli.rb:61:in `block in run'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/pronto-0.9.3/lib/pronto/cli.rb:60:in `chdir'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/pronto-0.9.3/lib/pronto/cli.rb:60:in `run'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/share/rvm/gems/ruby-2.3.0/gems/pronto-0.9.3/bin/pronto:6:in `<top (required)>'
	from /usr/share/rvm/gems/ruby-2.3.0/bin/pronto:22:in `load'
	from /usr/share/rvm/gems/ruby-2.3.0/bin/pronto:22:in `<main>'
	from /usr/share/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/share/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by nagarjunac** [comment]
Sorry used GITHUB_ACCESS_TOKEN instead of PRONTO_GITHUB_ACCESS_TOKEN
