### ISSUE TITLE
Issue while running pronto inside my rails application

### ISSUE THREAD

**Issue by balogic** [prontolabs/pronto#252]
I've installed `pronto-0.9.4` and tried to run `pronto run` after navigating to my repository. I've got this error while doing so.
```
/home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/version.rb:354:in `===': class or module required (TypeError)
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/version.rb:354:in `<=>'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/requirement.rb:24:in `>='
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/requirement.rb:24:in `block in <class:Requirement>'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/requirement.rb:243:in `block in satisfied_by?'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/requirement.rb:243:in `each'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/requirement.rb:243:in `all?'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/requirement.rb:243:in `satisfied_by?'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:280:in `block in matching_specs'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:279:in `each'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:279:in `find_all'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:279:in `matching_specs'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:300:in `to_specs'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1065:in `block in find_in_unresolved'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1065:in `map'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1065:in `find_in_unresolved'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/adapter/net_http.rb:7:in `<top (required)>'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday.rb:220:in `block in load_middleware'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday.rb:194:in `middleware_mutex'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday.rb:215:in `load_middleware'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday.rb:185:in `lookup_middleware'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:204:in `use_symbol'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:100:in `adapter'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/octokit-4.7.0/lib/octokit/default.rb:31:in `block in <module:Default>'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:66:in `build'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:55:in `initialize'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/octokit-4.7.0/lib/octokit/default.rb:27:in `new'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/octokit-4.7.0/lib/octokit/default.rb:27:in `<module:Default>'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/octokit-4.7.0/lib/octokit/default.rb:9:in `<module:Octokit>'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/octokit-4.7.0/lib/octokit/default.rb:6:in `<top (required)>'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/octokit-4.7.0/lib/octokit.rb:4:in `<top (required)>'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pronto-0.9.4/lib/pronto.rb:2:in `<top (required)>'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/balvis/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pronto-0.9.4/bin/pronto:3:in `<top (required)>'
	from /home/balvis/.rbenv/versions/2.3.0/bin/pronto:22:in `load'
	from /home/balvis/.rbenv/versions/2.3.0/bin/pronto:22:in `<main>'
```

Ruby - `2.3.0`
Rails - `5.0.4`
Bundler - `1.15.1`

**Comment by ivanovaleksey** [comment]
Hi @balogic, could you show `rubygems` version with `gem --version`?

**Comment by balogic** [comment]
@ivanovaleksey My `rubygems` version is `2.6.10`

**Comment by ivanovaleksey** [comment]
I am not sure but it looks like the problem is with rubygems not pronto gem.

In `rubygems/version.rb:354` we have 
```
return -1 if String  === lhs && Numeric === rhs
```
and the error message
> class or module required (TypeError)

smells like there is problem with parentheses

@balogic could you experiment with it yourself?
You can open `/home/balvis/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/version.rb` with you favorite text editor and replace line 354 with

```
return -1 if String.===(lhs) && Numeric.===(rhs)
```

and then run pronto again.

**Comment by balogic** [comment]
@ivanovaleksey I've tried. Again the same error stays.

**Comment by ivanovaleksey** [comment]
@balogic are you sure about line numbers, because there is similar code in line 355?
Can you inspect values of `lhs` and `rhs`?

**Comment by balogic** [comment]
@ivanovaleksey I've inspected and both the values are `0`

**Comment by ivanovaleksey** [comment]
@balogic to be honest I don't what else can cause the issue 😐

**Comment by mmozuras** [comment]
@balogic do you get the same error with newer Ruby version, for example 2.3.4 or 2.4.0?

**Comment by ashkulz** [comment]
Mass-closure of old issues more than 4 years old, please reopen and/or comment if this is still valid.
