### ISSUE TITLE
Error while configuring with bitbucket

### ISSUE THREAD

**Issue by sunasra** [prontolabs/pronto#265]
in .pronto.yml

`all:`
`  exclude:`
`   - 'spec/**/*'`
`# exclude files for single runner`
`bitbucket:`
`  slug: username/repo`
` username: example@test.com`
`  password: xxxxxxx`
`  web_endpoint: https://bitbucket.org/`
`max_warnings: 150`
`verbose: true``

running this command in local
`bundle exec pronto run -f bitbucket_pr -c origin/<branch_name>`

throws this error
```
/Users/abcuser/.rvm/gems/ruby-2.1.6/gems/pronto-0.9.5/lib/pronto/clients/bitbucket_client.rb:26:in `pull_requests': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/gems/pronto-0.9.5/lib/pronto/bitbucket.rb:68:in `pull_requests'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/gems/pronto-0.9.5/lib/pronto/bitbucket.rb:61:in `pull'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/gems/pronto-0.9.5/lib/pronto/bitbucket.rb:54:in `pull_id'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/gems/pronto-0.9.5/lib/pronto/bitbucket.rb:4:in `pull_comments'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/gems/pronto-0.9.5/lib/pronto/formatter/pull_request_formatter.rb:6:in `existing_comments'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/gems/pronto-0.9.5/lib/pronto/formatter/git_formatter.rb:6:in `format'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/gems/pronto-0.9.5/lib/pronto.rb:67:in `block in run'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/gems/pronto-0.9.5/lib/pronto.rb:66:in `each'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/gems/pronto-0.9.5/lib/pronto.rb:66:in `run'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/gems/pronto-0.9.5/lib/pronto/cli.rb:61:in `block in run'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `chdir'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `run'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/gems/pronto-0.9.5/bin/pronto:6:in `<top (required)>'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/bin/pronto:23:in `load'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/bin/pronto:23:in `<main>'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `eval'
	from /Users/abcuser/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `<main>'
```

Can anyone let me know what is issue here

**Comment by mmozuras** [comment]
@sunasra hey, thanks for reporting the issue. It might be a bug with Pronto not handling zero open pull requests. At the time of running the script, did you have any pull requests open?

**Comment by sunasra** [comment]
@mmozuras Thanks for Reply.
Pull request is open for branch passed in command. i.e bundle exec pronto run -f bitbucket_pr -c origin/<branch_name>

**Comment by nbekirov** [comment]
Without actually being able to run the code now and using a public repo (`mailchimp/mandrill-api-ruby`) I think that [bitbucket_client.rb](https://github.com/prontolabs/pronto/blob/master/lib/pronto/clients/bitbucket_client.rb#L23) will try to GET `https://api.bitbucket.org/1.0/repositories/mailchimp/mandrill-api-ruby/pullrequests?state=OPEN` which results in

```bash
$ curl -I https://api.bitbucket.org/1.0/repositories/mailchimp/mandrill-api-ruby/pullrequests?state=OPEN
HTTP/1.1 404 Not Found
Server: nginx
Vary: Authorization
Cache-Control: max-age=900
Content-Type: application/json; charset=utf-8
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Date: Thu, 19 Oct 2017 11:56:28 GMT
X-Served-By: app-139
X-Static-Version: d340220bdad7
ETag: "2b62f73138bb745c0a65d30d15361a22"
X-Render-Time: 0.00587797164917
Connection: keep-alive
X-Version: d340220bdad7
X-Request-Count: 428
X-Frame-Options: SAMEORIGIN
X-Cache-Info: caching
Content-Length: 243
```

Changin the API version to `2.0` yields 

```bash
$ curl -I https://api.bitbucket.org/2.0/repositories/mailchimp/mandrill-api-ruby/pullrequests?state=OPEN
HTTP/1.1 200 OK
Server: nginx
Vary: Authorization, Accept-Encoding
Cache-Control: max-age=900
Content-Type: application/json; charset=utf-8
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Date: Thu, 19 Oct 2017 11:56:34 GMT
X-Served-By: app-140
Accept-Ranges: bytes
ETag: "ac328158e28563e8a94427b83c782eba"
X-Static-Version: d340220bdad7
X-Content-Type-Options: nosniff
X-Accepted-OAuth-Scopes: pullrequest
X-Render-Time: 0.113039970398
Connection: keep-alive
X-Request-Count: 501
X-Version: d340220bdad7
X-Frame-Options: SAMEORIGIN
X-Cache-Info: caching
Content-Length: 19174
```

**Comment by mmozuras** [comment]
@sunasra I can't reproduce it myself. Could you logging to BitbucketClient or use something like [pry](https://github.com/pry/pry) to inspect the `response`?

This is the code we're interested in:

```ruby
class BitbucketClient
  # ...

  def pull_requests(slug)
    base = 'https://api.bitbucket.org/2.0/repositories'
    response = get("#{base}/#{slug}/pullrequests?state=OPEN")
    openstruct(response['values'])
  end

 # ...
end
```

**Comment by matt-hh** [comment]
Hi, 

running into the same issue... 🙈

You can reproduce it with your account password, but you need to create an app password...
https://developer.atlassian.com/bitbucket/api/2/reference/meta/authentication#basic-auth

This issue can be closed.

**Comment by tevariou** [comment]
I'm running into the same issue as OP
@sunasra did you simply fix it opening a PR?

**Comment by ashkulz** [comment]
Mass-closure of old issues more than 4 years old, please reopen and/or comment if this is still valid.
