### ISSUE TITLE
Gitlab integration stopped to work

### ISSUE THREAD

**Issue by sauliusgrigaitis** [prontolabs/pronto#274]
It doesn't work since 9.0 release.

```
PRONTO_GITLAB_API_PRIVATE_TOKEN="..." PRONTO_GITLAB_API_ENDPOINT="https://.../api/v3" bundle exec pronto run -f gitlab -c origin/develop
/home/saulius/.rvm/gems/ruby-2.4.2/gems/gitlab-4.2.0/lib/gitlab/request.rb:80:in `validate': Server responded with code 404, message: 404 Project Not Found. Request URI: https://.../api/v3/projects/company%252Fproject/repository/commits/22327dc6a9cba45b81c49e0da2baa832ac9184c0/comments (Gitlab::Error::NotFound)
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/gitlab-4.2.0/lib/gitlab/request.rb:43:in `get'
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/gitlab-4.2.0/lib/gitlab/client/commits.rb:61:in `commit_comments'
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/pronto-0.9.5/lib/pronto/gitlab.rb:5:in `commit_comments'
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `block in existing_comments'
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `each'
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `flat_map'
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `existing_comments'
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/pronto-0.9.5/lib/pronto/formatter/git_formatter.rb:6:in `format'
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/pronto-0.9.5/lib/pronto.rb:67:in `block in run'
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/pronto-0.9.5/lib/pronto.rb:66:in `each'
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/pronto-0.9.5/lib/pronto.rb:66:in `run'
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/pronto-0.9.5/lib/pronto/cli.rb:61:in `block in run'
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `chdir'
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `run'
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  from /home/saulius/.rvm/gems/ruby-2.4.2/gems/pronto-0.9.5/bin/pronto:6:in `<top (required)>'
  from /home/saulius/.rvm/gems/ruby-2.4.2/bin/pronto:23:in `load'
  from /home/saulius/.rvm/gems/ruby-2.4.2/bin/pronto:23:in `<main>'
  from /home/saulius/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
  from /home/saulius/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by sauliusgrigaitis** [comment]
The solution is to replace `%2F` with `/` in Gitlab slug.
