### ISSUE TITLE
Doesn't generate messages with gitlab format

### ISSUE THREAD

**Issue by brunofrank** [prontolabs/pronto#299]
Pronto doesn't work just when the formmater is gitlab, I tried to figued it out, but everything looks good to me.

## Gemfile
```
  gem 'pronto'
  gem 'pronto-brakeman', require: false
  gem 'pronto-flay', require: false
  gem 'pronto-reek', require: false
  gem 'pronto-rubocop', require: false
```

## Command
`bundle exec pronto run -c origin/master -f gitlab`

## pronto.yml
```
eslint:
  exclude:
    - 'app/assets/**/*'
    - 'vendor/assets/**/*'
max_warnings: 150
verbose: true
gitlab:
  slug: [PRIVATE]
  api_private_token: [PRIVATE]
```
## Stack
```
gems/pronto-0.9.5/lib/pronto/formatter/git_formatter.rb:39:in `block in grouped_comments': undefined method `path' for nil:NilClass (NoMethodError)
	from gems/pronto-0.9.5/lib/pronto/formatter/git_formatter.rb:39:in `each'
	from gems/pronto-0.9.5/lib/pronto/formatter/git_formatter.rb:39:in `group_by'
	from gems/pronto-0.9.5/lib/pronto/formatter/git_formatter.rb:39:in `grouped_comments'
	from gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:7:in `existing_comments'
	from gems/pronto-0.9.5/lib/pronto/formatter/git_formatter.rb:6:in `format'
	from gems/pronto-0.9.5/lib/pronto.rb:67:in `block in run'
	from gems/pronto-0.9.5/lib/pronto.rb:66:in `each'
	from gems/pronto-0.9.5/lib/pronto.rb:66:in `run'
	from gems/pronto-0.9.5/lib/pronto/cli.rb:61:in `block in run'
	from gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `chdir'
	from gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `run'
	from gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from gems/pronto-0.9.5/bin/pronto:6:in `<top (required)>'
	from bin/pronto:23:in `load'
	from bin/pronto:23:in `<main>'
	from bin/ruby_executable_hooks:15:in `eval'
	from bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by xBartu** [comment]
Does anybody working on it?

**Comment by dsander** [comment]
This is probably related to GitLab [removing API version 3 support in GitLab 11.0](https://docs.gitlab.com/ee/api/v3_to_v4.html). We were able to fix our setup by changing the API version to `v4` in `PRONTO_GITLAB_API_ENDPOINT`
