### ISSUE TITLE
f2018071301 - Add option for warnings per pr review

### ISSUE THREAD

**Issue by dimitrovv** [prontolabs/pronto#302]
I would like to suggest a feature that will allow **limiting** the number of comment per **PR** review.
Currently, we are experiencing issues creating **PR reviews** in case the comments to publish are more (ex **100** etc). We are using the `github_pr_review` to publish comments to a **Github Enterprise** PR.

I suspect the **GHE** is not able to serve this request and returns **502**.
I believe this option will allow us to split the **PR** reviews and have smaller **PR** reviews.

-------

<details>
<summary>Backtrace</summary>

```ruby
PRONTO_GITHUB_ACCESS_TOKEN=access_token_here PRONTO_PULL_REQUEST_ID=1901 bin/pronto run -f github_pr_review -c origin/develop

warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/octokit-4.8.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://github-url.com/api/v3/repos/slug-here/pulls/1901/reviews: 502 - <!DOCTYPE html> (Octokit::BadGateway)
...
from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/faraday-0.15.2/lib/faraday/response.rb:9:in `block in call'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/faraday-0.15.2/lib/faraday/response.rb:61:in `on_complete'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/octokit-4.8.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/octokit-4.8.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/faraday-0.15.2/lib/faraday/connection.rb:175:in `post'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/octokit-4.8.0/lib/octokit/connection.rb:156:in `request'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/octokit-4.8.0/lib/octokit/connection.rb:28:in `post'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/octokit-4.8.0/lib/octokit/client/reviews.rb:93:in `create_pull_request_review'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/pronto-0.9.5/lib/pronto/github.rb:51:in `create_pull_request_review'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/pronto-0.9.5/lib/pronto/formatter/github_pull_request_review_formatter.rb:13:in `submit_comments'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/pronto-0.9.5/lib/pronto/formatter/git_formatter.rb:9:in `format'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/pronto-0.9.5/lib/pronto.rb:67:in `block in run'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/pronto-0.9.5/lib/pronto.rb:66:in `each'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/pronto-0.9.5/lib/pronto.rb:66:in `run'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/pronto-0.9.5/lib/pronto/cli.rb:61:in `block in run'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `chdir'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `run'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/ventsislav.dimitrov/.rvm/gems/ruby-x.x.x/gems/pronto-0.9.5/bin/pronto:6:in `<top (required)>'
	from bin/pronto:18:in `load'
	from bin/pronto:18:in `<main>'
```

</details>

**Comment by dimitrovv** [comment]
@doomspork, @mmozuras, thx for reviewing & merge. WDYT, is it possible to bump the version so we start using this feature?

**Comment by doomspork** [comment]
Howdy @dimitrovv, I'd _love_ to close out a couple more outstanding PRs before cutting a new release. If you have some time to review the outstanding PRs I'd love to get your thoughts.

We're always looking for new org members 😉

**Comment by dimitrovv** [comment]
> If you have some time to review the outstanding PRs I'd love to get your thoughts

I would love to, all we need is time 😉
