### ISSUE TITLE
Gitlab CI integration isse

### ISSUE THREAD

**Issue by exu** [prontolabs/pronto#307]
Hello, 

I have issue with posting changes to gitlab, credo and pronto installed properly, credo is returning issues properly. 

The same issue occurs on local and docker environent. 

Ruby 2.5.1, pronto 0.9.5

Some ideas what I'm missing out ? 

`/home/exu/.gem/ruby/2.5.0/gems/gitlab-4.4.0/lib/gitlab/objectified_hash.rb:26:in `method_missing': wrong number of arguments (given 2, expected 1) (ArgumentError)`

```
PRONTO_GITLAB_API_ENDPOINT=https://gitlab.*****.someinstance.com/api/v4 PRONTO_GITLAB_API_PRIVATE_TOKEN=XXXXXXX pronto run -c HEAD~ -f gitlab 
Traceback (most recent call last):
	26: from /home/exu/.gem/ruby/2.5.0/bin/pronto:23:in `<main>'
	25: from /home/exu/.gem/ruby/2.5.0/bin/pronto:23:in `load'
	24: from /home/exu/.gem/ruby/2.5.0/gems/pronto-0.9.5/bin/pronto:6:in `<top (required)>'
	23: from /home/exu/.gem/ruby/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	22: from /home/exu/.gem/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	21: from /home/exu/.gem/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	20: from /home/exu/.gem/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	19: from /home/exu/.gem/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `run'
	18: from /home/exu/.gem/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `chdir'
	17: from /home/exu/.gem/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto/cli.rb:61:in `block in run'
	16: from /home/exu/.gem/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto.rb:66:in `run'
	15: from /home/exu/.gem/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto.rb:66:in `each'
	14: from /home/exu/.gem/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto.rb:67:in `block in run'
	13: from /home/exu/.gem/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto/formatter/git_formatter.rb:6:in `format'
	12: from /home/exu/.gem/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `existing_comments'
	11: from /home/exu/.gem/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `flat_map'
	10: from /home/exu/.gem/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `each'
	 9: from /home/exu/.gem/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `block in existing_comments'
	 8: from /home/exu/.gem/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto/gitlab.rb:5:in `commit_comments'
	 7: from /home/exu/.gem/ruby/2.5.0/gems/gitlab-4.4.0/lib/gitlab/client/commits.rb:61:in `commit_comments'
	 6: from /home/exu/.gem/ruby/2.5.0/gems/gitlab-4.4.0/lib/gitlab/request.rb:44:in `block (2 levels) in <class:Request>'
	 5: from /home/exu/.gem/ruby/2.5.0/gems/gitlab-4.4.0/lib/gitlab/request.rb:64:in `validate'
	 4: from /home/exu/.gem/ruby/2.5.0/gems/gitlab-4.4.0/lib/gitlab/request.rb:64:in `raise'
	 3: from /home/exu/.gem/ruby/2.5.0/gems/gitlab-4.4.0/lib/gitlab/request.rb:64:in `exception'
	 2: from /home/exu/.gem/ruby/2.5.0/gems/gitlab-4.4.0/lib/gitlab/error.rb:16:in `initialize'
	 1: from /home/exu/.gem/ruby/2.5.0/gems/gitlab-4.4.0/lib/gitlab/error.rb:40:in `build_error_message'
/home/exu/.gem/ruby/2.5.0/gems/gitlab-4.4.0/lib/gitlab/objectified_hash.rb:26:in `method_missing': wrong number of arguments (given 2, expected 1) (ArgumentError)
```

**Comment by ashkulz** [comment]
Mass-closure of old issues more than 4 years old, please reopen and/or comment if this is still valid.
