### ISSUE TITLE
Gitlab integration error

### ISSUE THREAD

**Issue by max-konin** [prontolabs/pronto#310]
Hi.

I'm using Gitlab.com's hosted service. 
pronto version - 0.9.5
Error:
```
$ PRONTO_GITLAB_API_PRIVATE_TOKEN=$GITLAB_API_PRIVATE_TOKEN pronto run -f gitlab -c origin/development
/usr/local/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect': Failed to open TCP connection to :80 (Network is unreachable - connect(2) for nil port 80) (Errno::ENETUNREACH)
	from /usr/local/lib/ruby/2.4.0/net/http.rb:903:in `block in connect'
	from /usr/local/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
	from /usr/local/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
	from /usr/local/lib/ruby/2.4.0/net/http.rb:902:in `connect'
	from /usr/local/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
	from /usr/local/lib/ruby/2.4.0/net/http.rb:876:in `start'
	from /usr/local/lib/ruby/2.4.0/net/http.rb:1407:in `request'
	from /usr/local/bundle/gems/httparty-0.16.2/lib/httparty/request.rb:143:in `perform'
	from /usr/local/bundle/gems/httparty-0.16.2/lib/httparty.rb:563:in `perform_request'
	from /usr/local/bundle/gems/httparty-0.16.2/lib/httparty.rb:489:in `get'
	from /usr/local/bundle/gems/gitlab-4.5.0/lib/gitlab/request.rb:44:in `block (2 levels) in <class:Request>'
	from /usr/local/bundle/gems/gitlab-4.5.0/lib/gitlab/client/commits.rb:61:in `commit_comments'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto/gitlab.rb:5:in `commit_comments'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `block in existing_comments'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `each'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `flat_map'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `existing_comments'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto/formatter/git_formatter.rb:6:in `format'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto.rb:67:in `block in run'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto.rb:66:in `each'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto.rb:66:in `run'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto/cli.rb:61:in `block in run'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `chdir'
	from /usr/local/bundle/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `run'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/bundle/gems/pronto-0.9.5/bin/pronto:6:in `<top (required)>'
	from /usr/local/bundle/bin/pronto:23:in `load'
	from /usr/local/bundle/bin/pronto:23:in `<main>'
```

**Comment by ashkulz** [comment]
Mass-closure of old issues more than 4 years old, please reopen and/or comment if this is still valid.
