### ISSUE TITLE
Method missing with gitlab

### ISSUE THREAD

**Issue by Apelsinka223** [prontolabs/pronto#317]
Hi, got error with gitlab integration

ruby - 2.3
gitlab - 4.6.1
pronto - 0.9.5

```
> PRONTO_GITLAB_API_PRIVATE_TOKEN=$PRONTO_GITLAB_API_PRIVATE_TOKEN pronto run -f gitlab -c origin/develop

/Library/Ruby/Gems/2.3.0/gems/gitlab-4.6.1/lib/gitlab/objectified_hash.rb:28:in `method_missing': undefined method `map' for #<Gitlab::ObjectifiedHash:0x00007fc3bbac02e8> (NoMethodError)
Did you mean?  tap
	from /Library/Ruby/Gems/2.3.0/gems/pronto-0.9.5/lib/pronto/gitlab.rb:5:in `commit_comments'
	from /Library/Ruby/Gems/2.3.0/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `block in existing_comments'
	from /Library/Ruby/Gems/2.3.0/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `flat_map'
	from /Library/Ruby/Gems/2.3.0/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `existing_comments'
	from /Library/Ruby/Gems/2.3.0/gems/pronto-0.9.5/lib/pronto/formatter/git_formatter.rb:6:in `format'
	from /Library/Ruby/Gems/2.3.0/gems/pronto-0.9.5/lib/pronto.rb:67:in `block in run'
	from /Library/Ruby/Gems/2.3.0/gems/pronto-0.9.5/lib/pronto.rb:66:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/pronto-0.9.5/lib/pronto.rb:66:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/pronto-0.9.5/lib/pronto/cli.rb:61:in `block in run'
	from /Library/Ruby/Gems/2.3.0/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/pronto-0.9.5/bin/pronto:6:in `<top (required)>'
	from /usr/local/bin/pronto:22:in `load'
	from /usr/local/bin/pronto:22:in `<main>'
```

**Comment by remz99** [comment]
I ran into the same error recently and by setting the api_endpoint in my pronto config for gitlab to `https://gitlab.com/api/v4` resolved it.  The pull request(https://github.com/prontolabs/pronto/pull/298) to fix this is still unreleased https://github.com/prontolabs/pronto/blob/master/CHANGELOG.md

**Comment by mknapik** [comment]
@Apelsinka223 Feel free to reopen the issue if you're getting the same error when using the newest version from master.

**Comment by xBartu** [comment]
I am getting exactly the same problem, background info, I just got the release from the Github and updated gem locks. Any update on that issue?

**Comment by sobolevn** [comment]
I am also getting this with `0.9.5`

**Comment by mmozuras** [comment]
@sobolevn could you check if that's still the case with `0.10.0`?

**Comment by sobolevn** [comment]
@mmozuras well, I actually cannot update, since a lot of plugins (`json`, `yaml`, `spell`) relies on `0.9.5`. I have opened several issues to upgrade the versions.
