### ISSUE TITLE
Octokit::UnprocessableEntity - No commit found for SHA

### ISSUE THREAD

**Issue by jdq22** [prontolabs/pronto#353]
I'm using Pronto with CircleCI and GitHub. On July 30, 2019, our CircleCI jobs started failing because of this error:
```#!/bin/bash -eo pipefail
[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow
PRONTO_PULL_REQUEST_ID=${CIRCLE_PULL_REQUEST} bundle exec pronto run -f github github_status github_pr -c origin/master
bundler: failed to load command: pronto (/home/circleci/network/vendor/bundle/ruby/2.5.0/bin/pronto)
Octokit::UnprocessableEntity: GET https://api.github.com/repos/FirstRoundCapital/network/commits//comments?per_page=100: 422 - No commit found for SHA: /comments // See: https://developer.github.com/v3/repos/commits/#get-a-single-commit
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/octokit-4.7.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/octokit-4.7.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/octokit-4.7.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/octokit-4.7.0/lib/octokit/connection.rb:156:in `request'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/octokit-4.7.0/lib/octokit/connection.rb:84:in `paginate'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/octokit-4.7.0/lib/octokit/client/commit_comments.rb:25:in `commit_comments'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto/github.rb:18:in `commit_comments'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `block in existing_comments'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `each'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `flat_map'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto/formatter/commit_formatter.rb:6:in `existing_comments'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto/formatter/git_formatter.rb:6:in `format'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto.rb:67:in `block in run'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto.rb:66:in `each'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto.rb:66:in `run'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto/cli.rb:61:in `block in run'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `chdir'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/pronto-0.9.5/lib/pronto/cli.rb:60:in `run'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/gems/pronto-0.9.5/bin/pronto:6:in `<top (required)>'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/bin/pronto:23:in `load'
  /home/circleci/network/vendor/bundle/ruby/2.5.0/bin/pronto:23:in `<top (required)>'
Exited with code 1
```

I'm also able to reproduce this error locally.

**Comment by jdq22** [comment]
I figured out the error was coming from `pronto-eslint`. Closing this.

**Comment by abinoam** [comment]
Hi @jdq22 

I'm having the same error.
Disabling `pronto-eslint` have solved it. Thanks!
Any details more?
