### ISSUE TITLE
Rugged::OdbError when integrating with Github actions

### ISSUE THREAD

**Issue by Fahmiin-Abdullah** [prontolabs/pronto#392]
Hello!

I've got this error when I tried integrating pronto into github actions
```
/opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/pronto-0.10.0/lib/pronto/git/repository.rb:87:in `merge_base': object not found - no match for id (ae447230dd5fcb409c863f43dde39b8d6d176323) (Rugged::OdbError)
	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/pronto-0.10.0/lib/pronto/git/repository.rb:87:in `merge_base'
	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/pronto-0.10.0/lib/pronto/git/repository.rb:17:in `diff'
	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/pronto-0.10.0/lib/pronto.rb:62:in `run'
	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/pronto-0.10.0/lib/pronto/cli.rb:66:in `block in run'
	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/pronto-0.10.0/lib/pronto/cli.rb:64:in `chdir'
	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/pronto-0.10.0/lib/pronto/cli.rb:64:in `run'
	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/pronto-0.10.0/bin/pronto:6:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.6.5/x64/bin/pronto:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.6.5/x64/bin/pronto:23:in `<main>'
Error: Process completed with exit code 1.
```

Unsure if this is a pronto issue or what. First sighted in our pipeline 16 days ago. The workflow was working normally before though.

**Comment by Fahmiin-Abdullah** [comment]
UPDATE: I've changed `--depth=10` flag to `--unshallow` and that seems to fix it for me.
