### ISSUE TITLE
Pronto does nothing silently; rubocop and rails_best_pratices report errors

### ISSUE THREAD

**Issue by skwp** [prontolabs/pronto#65]
I can confirm that rubocop and rails_best_practices both return a handful of errors, however running pronto results in zero comments both in its normal mode (pronto run master) and github mode (GITHUB_ACCESS_TOKEN=[....] PULL_REQUEST_ID=3147 pronto run -f github_pr)

Has anyone experienced this? Ruby 2.1.1 / Rails 4.1

**Comment by skwp** [comment]
Contents of Gemfile:
```
gem 'pronto'
gem 'pronto-rubocop', require: false  #Ruby styleguide
gem 'pronto-rails_best_practices', require: false  #Ruby styleguide
```

Gemfile.lock
```
pronto (0.4.1)
    pronto-brakeman (0.4.0)
      pronto (~> 0.4.0)
    pronto-haml (0.4.0)
      pronto (~> 0.4.0)
    pronto-jshint (0.4.0)
      pronto (~> 0.4.0)
    pronto-rails_best_practices (0.4.0)
      pronto (~> 0.4.0)
    pronto-reek (0.4.0)
      pronto (~> 0.4.0)
    pronto-rubocop (0.4.0)
      pronto (~> 0.4.0)
    pronto-scss (0.4.0)
      pronto (~> 0.4.0)
```

**Comment by eliotsykes** [comment]
Apologies if this isn't related. I've had pronto report nothing when I'm on a branch that has uncommitted changes, or if there are little or no changes from master. Specifying one of these options helped:

```bash
# Have pronto analyze entire project since very first commit
pronto run --commit=$(git log --pretty=format:%H | tail -1)

# Have pronto analyze uncommitted changes
pronto run --index
```

**Comment by mmozuras** [comment]
@skwp did @eliotsykes answer helped? Do you still encounter this issue with the current release (0.8.2)?

**Comment by LucasHMonteiro** [comment]
Hello, I have the same issue here. My project is up to date and have no changes to commit. The only runners that I'm using that work along with pronto are flay, rubocop and poper. The others like reek or brakeman report lots of things when used separetely from pronto but report nothing when used along with it

**Comment by mmozuras** [comment]
@LucasHMonteiro did you try to run in a (feature/development) branch with changes or `master`?

**Comment by LucasHMonteiro** [comment]
@mmozuras I ran it in a feature/development branch and it worked well (except for brakeman that seems to have some problems on its own) and in the master branch it throws a NoMethodError for "this" method in the specifcation.rb file in the rubygems folder. So let me see if I got it, pronto will only work properly in a branch that has the "feature/" prefix?

**Comment by mmozuras** [comment]
@LucasHMonteiro could you post the stacktrace for the error?

Pronto is not supposed to be used on `master`. But I'd like to understand if there's a way to improve. What kind of behaviour did you expect?

**Comment by LucasHMonteiro** [comment]
@mmozuras here goes the full stack trace

`/home/sti/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0xc75970 pronto-0.8.2> (NoMethodError)
        from /home/sti/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
        from /home/sti/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
        from /home/sti/.rvm/gems/ruby-2.3.1/gems/pronto-rails_best_practices-0.8.0/lib/pronto/rails_best_practices.rb:1:in `<top (required)>'
        from /home/sti/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /home/sti/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /home/sti/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /home/sti/.rvm/gems/ruby-2.3.1/gems/pronto-0.8.2/lib/pronto/cli.rb:47:in `block in run'
        from /home/sti/.rvm/gems/ruby-2.3.1/gems/pronto-0.8.2/lib/pronto/cli.rb:46:in `each'
        from /home/sti/.rvm/gems/ruby-2.3.1/gems/pronto-0.8.2/lib/pronto/cli.rb:46:in `run'
        from /home/sti/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /home/sti/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/sti/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /home/sti/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /home/sti/.rvm/gems/ruby-2.3.1/gems/pronto-0.8.2/bin/pronto:6:in `<top (required)>'
        from /home/sti/.rvm/gems/ruby-2.3.1/bin/pronto:23:in `load'
        from /home/sti/.rvm/gems/ruby-2.3.1/bin/pronto:23:in `<main>'
        from /home/sti/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /home/sti/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'`

I'm not intending to run pronto on ´master´, just did it cause you mentioned it and wanted to see the behavior.

**Comment by ashkulz** [comment]
Mass-closure of old issues more than 4 years old, please reopen and/or comment if this is still valid.
