### ISSUE TITLE
Problem when handling submodule changes

### ISSUE THREAD

**Issue by siebertm** [prontolabs/pronto#76]
I have a repository with certain submodules. When I let pronto review a commit which changes a submodule, I get an error:

```
/home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.1/lib/pronto/runner.rb:16:in `readline': Is a directory @ io_fillbuf - fd:9 /home/gitlab-runner/tmp/builds/project-1/app/assets/javascripts/lib/edifact.js (Errno::EISDIR)
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.1/lib/pronto/runner.rb:16:in `block in ruby_executable?'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.1/lib/pronto/runner.rb:16:in `open'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.1/lib/pronto/runner.rb:16:in `ruby_executable?'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.1/lib/pronto/runner.rb:10:in `ruby_file?'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-rubocop-0.4.0/lib/pronto/rubocop.rb:16:in `block in run'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.1/lib/pronto/git/patches.rb:15:in `each'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.1/lib/pronto/git/patches.rb:15:in `each'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-rubocop-0.4.0/lib/pronto/rubocop.rb:14:in `select'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-rubocop-0.4.0/lib/pronto/rubocop.rb:14:in `run'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.1/lib/pronto.rb:60:in `block in run_all_runners'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.1/lib/pronto.rb:59:in `map'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.1/lib/pronto.rb:59:in `run_all_runners'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.1/lib/pronto.rb:34:in `run'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.1/lib/pronto/cli.rb:52:in `run'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pronto-0.4.1/bin/pronto:6:in `<top (required)>'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/bin/pronto:23:in `load'
    from /home/gitlab-runner/.rbenv/versions/2.1.5/bin/pronto:23:in `<main>'
```

What I think is happening is that pronto is not checking if the changed items are files or not (=> submodules are directories)

**Comment by lunks** [comment]
I'm getting the same error.

**Comment by Schwad** [comment]
@siebertm I have no idea at all if it's related but I have had some issues with the gitlab integration on pronto. Do you have an 'example app' or something similar where we can replicate this error?

**Comment by siebertm** [comment]
Well, this was 2 years ago, we don't use submodules anymore... (they are evil :-p)

So, I have no stakes anymore in this issue...
(could be closed if it was for me)
